MVCProjeKampi/Controllers/AdminCategoryController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCProjeKampi.Controllers
{
    public class AdminCategoryController : Controller
    {
        CategoryManager cm = new CategoryManager(new EfCategoryDal());

        [Authorize] //Sadece B Rolüne sahip olan göstersin
        public ActionResult Index()
        {
            var categoryValues = cm.GetList();
            return View(categoryValues);
        }
        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddCategory(Category p)
        {
            CategoryValidator categoryValidator = new CategoryValidator();
            ValidationResult result = categoryValidator.Validate(p);
            if(result.IsValid)
            {
                cm.CategoryAddBL(p);
                TempData["AddCategory"] = "Başarılı";
                return RedirectToAction("Index");
            }
            else
            {
                foreach(var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        public ActionResult DeleteCategory(int id)
        {
            var categoryValue = cm.GetByID(id);
            cm.CategoryDelete(categoryValue);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult EditCategory(int id)
        {
            var categoryValue = cm.GetByID(id);
            return View(categoryValue);
        }
        [HttpPost]
        public ActionResult EditCategory(Category p)
        {
            cm.CategoryUpdate(p);
            return RedirectToAction("Index");
        }

    }
}

MVCProjeKampi/Views/AdminCategory/AddCategory.cshtml
@model EntityLayer.Concrete.Category
@{
    ViewBag.Title = "AddCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Yeni kategori ekleme sayfası</h1>
<br />
@using (Html.BeginForm("AddCategory", "AdminCategory", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryName)
        <br /><br />
        @Html.Label("Açıklama Yazınız")
        @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryDescription)
        <button class="btn btn-info">Kaydet</button>
    </div>


}
@if (TempData["AddCategory"] != null)
{
    <script type="text/javascript">
        window.onload = function () {
            swal("Kategori Ekleme Durumu", "Başarılı", "success");
        };
</script>
}

MVCProjeKampi/Views/AdminCategory/EditCategory.cshtml
@model EntityLayer.Concrete.Category
@{
    ViewBag.Title = "EditCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Kategori Güncelleme Sayfası</h2>
@using (Html.BeginForm("EditCategory", "AdminCategory", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Kategori ID");
    @Html.TextBoxFor(x => x.CategoryID, new { @class = "form-control" })
    <br />
    @Html.Label("Kategori Adı");
    @Html.TextAreaFor(x => x.CategoryName, new { @class = "form-control" })
    <br />
    @Html.Label("Kategori Açıklaması");
    @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Güncelle</button>
</div>
}

MVCProjeKampi/Views/AdminCategory/Index.cshtml
@using EntityLayer.Concrete
@model List<Category>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<br />
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Kategori Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Başlıklar</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <th>@item.CategoryID</th>
            <td>@item.CategoryName</td>
            <td><a href="/AdminCategory/DeleteCategory/@item.CategoryID" class="btn btn-danger">Sil</a></td>
            <td><a href="/AdminCategory/EditCategory/@item.CategoryID" class="btn btn-warning">Güncelle</a></td>
            <td><a href="#" class="btn btn-primary">Başlıklar</a></td>
        </tr>
    }
</table>
<br />
<a href="/AdminCategory/AddCategory" class="btn btn-info">Yeni Kategori</a>
@if (TempData["AddCategory"] != null)
{
    <script type="text/javascript">
        window.onload = function () {
            swal("Kategori Ekleme Durumu", "Başarılı", "success");
        };
    </script>
}